# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangocms_moderation', '0002_auto_20180712_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderation',
            name='extended_object',
        ),
        migrations.RemoveField(
            model_name='moderation',
            name='public_extension',
        ),
        migrations.RemoveField(
            model_name='moderation',
            name='workflow',
        ),
        migrations.AddField(
            model_name='moderationcollection',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='author'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Moderation',
        ),
    ]
