# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0006_auto_20180618_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemoderationrequest',
            name='reference_number',
            field=models.CharField(db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
